version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: prj-backend
    ports:
      - "3001:3001"
    restart: always
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: prj-frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
